### PR TITLE
Add microdata markup for posts

### PR DESCRIPTION
**Pull request by aperezdc**
This is a first pass at adding schema.org Microdata markup to pages which use the `post` template. This adds inline metadata to the HTML markup which helps e.g. crawlers have a better view of content.

An introduction to Microdata can be found here: https://developer.mozilla.org/en-US/docs/Web/HTML/Microdata

----

Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/microdata/

### CODE REVIEW

**Comment by aperezdc** [comment]
I don't know if this is the best way of providing additional information to search engine crawlers, but mayor players like Google are behind the spec, so I expect this to help. This is only adding a few bits of metadata; if we want to go this way I can try to find more places where we could add Microdata markup and update the PR, or we can merge this and do follow-up PRs with more later 😺

**Comment by meyerweb** [comment]
At a first glance, the schema additions look correct, but the `meta` elements get injected into the document `body` rather than its `head`.  Is there a way to get the tags into the `head`?  I’m not 100% certain Google will honor the `meta` tags in their current place, and less certain that will continue to work in the future even if it does now.

**Comment by aperezdc** [comment]
> At a first glance, the schema additions look correct, but the `meta` elements get injected into the document `body` rather than its `head`. Is there a way to get the tags into the `head`? I’m not 100% certain Google will honor the `meta` tags in their current place, and less certain that will continue to work in the future even if it does now.

Using `<meta>` tags outside of `<head>` is not only possible, but sometimes it's the only option to add metadata which should not have a visual representation when a browser renders content. This is covered by the [Getting Started section of schema.org](https://schema.org/docs/gs.html#advanced_missing).

Finally, I have found Google's [structured data test tool](https://search.google.com/structured-data/testing-tool) and pointing it to some page from the preview site generated by the CI shows that it's picking the `<meta>` tags correctly (yay! 🙌️)

**Review by meyerweb — APPROVED** [review]

**Comment by aperezdc** [comment]
I have just noticed that even when the “new” (current) validator says in its [results](https://search.google.com/test/rich-results?id=AqOTJzbQmbrf3gQpB_zAqg) that all is fine, the “old” one's [results](https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Figalia.github.io%2Fwpewebkit.org%2Faperezdc%2Fmicrodata%2Fabout%2Fexploring.html) complain that the “publisher” entity should not be a “Thing”... I suppose that if the newer one is okay with the metadata, we can merge this as-is for now.

**Pull request merged**
