### PR TITLE
Add browsable site map

### PR DESCRIPTION
**Pull request by aperezdc**
This includes three commits:

1. Move stray WSAs to `/security/` (URLs are still the same, only the location in the file system changes).
2. Implement a site map page, which updates automatically. Pages can be excluded from it, which is probably nicer to maintain that manually having to add the pages to a list.
3. Add a site map link to to page footers.

Some notes from the second commit log message:

```
    Use the 11ty navigation plug-in, but instead of using its own
    eleventyNavigation filter add our own htmlSitemap one. The reason
    is that we want all pages except some, instead of only some which
    have been hand-picked (the default behaviour). The htmlSitemap
    filter picks all pages which:

     - Have a title, and
     - Are not skipped with "skipHtmlSitemap: true" in their data.

    Blog posts, release announcements, or security advisories, are skipped
    using their per-directory JSON data file (which sets "skipHtmlSitemap")
    to avoid having the long list of posts in the site map.

    A new Liquid+Markdown template generates the site map page. Styling for
    the lists used for navigation uses the custom lists-with-arrows from the
    "Learn & Discover" page with some spacing tweaks to make the page
    breathe some air.
```

----

Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/sitemap-page/

### CODE REVIEW

**Comment by aperezdc** [comment]
Screenshot, in case the preview won't work:

Screenshot 2024-03-06 at 17-38-56 Site Map

**Comment by mariospr** [comment]
@aperezdc I think it looks good in general but I have some specific comments:
  * I would follow the order of the top panel as much as possible, and put "Developers" right after "Blog"
  * What is "WPE"? If that's point to the "Get WPE" section then I'd rename it like that.
  * What is "Releases" pointing to?
    - If it's https://wpewebkit.org/release/schedule then it should say "Release Schedule"
    - If it's https://wpewebkit.org/releases then I think it should be "Releases"
  * "The Architecture of WPE" sounds a bit awkward, I think it should be "WPE Architecture".
    - While at this, I think we should change the header in https://wpewebkit.org/about/architecture.html which says "WPE Design" to "WPE Architecture" too, because it's a bit confusing when you load the page following a link that says "Architecture" (and because I think it's a better match).

**Comment by aperezdc** [comment]
> @aperezdc I think it looks good in general but I have some specific comments:
> 
> * I would follow the order of the top panel as much as possible, and put "Developers" right after "Blog"

We can reorder items adding a `htmlSitemapOrder: <num>` attribute to each page, there's already support for that. I'll add a commit that adds those as needed.

> * What is "WPE"? If that's point to the "Get WPE" section then I'd rename it like that.

That's the home page. I think it should be possible to override the link text in the sitemap, let me give it a try.

> * What is "Releases" pointing to?
>   
>   * If it's https://wpewebkit.org/release/schedule then it should say "Release Schedule"
>   * If it's https://wpewebkit.org/releases then I think it should be "Releases"

It points to `/release/`. Now that you mention it, I am not sure why `/release/schedule/` is not picked for inclusion in the site map... I'll take a look.

> * "The Architecture of WPE" sounds a bit awkward, I think it should be "WPE Architecture".
>   * While at this, I think we should change the header in https://wpewebkit.org/about/architecture.html which says "WPE Design" to "WPE Architecture" too, because it's a bit confusing when you load the page following a link that says "Architecture" (and because I think it's a better match).

Agreed. I'll do it in a separate commit in this PR. Or do we prefer a follow-up PR only with this change?

**Comment by aperezdc** [comment]
@mariospr All your comments have been addressed. Here's an updated screenshot:

Screenshot 2024-03-06 at 20-46-45 Site Map

**Comment by csaavedra** [comment]
Shouldn't the toplevel also have "Get WPE"?

**Comment by mariospr** [comment]
> @mariospr All your comments have been addressed. Here's an updated screenshot:

Yay, Looks great thanks!

The only bit that I'd fix now is to put "Get WPE" at a higher level in the hierarchy, and maybe after "Developers", but other than that the PR looks good.

Feel free to land it once that's fixed

**Review by mariospr — APPROVED** [review]

**Comment by aperezdc** [comment]
The “Get WPE” page is under `/about/` and the containing directory is used to determine where to put entries in the hierarchy. I'll try to allow manually setting the parent, like the original `eleventyNavigation` filter can do, so we can override where a page goes.

**Comment by aperezdc** [comment]
> The “Get WPE” page is under `/about/` and the containing directory is used to determine where to put entries in the hierarchy. I'll try to allow manually setting the parent, like the original `eleventyNavigation` filter can do, so we can override where a page goes.

Done, allowing to manually specify the parent in the sitemap for a page was easy in the end.

**Comment by aperezdc** [comment]
This is now live: https://wpewebkit.org/sitemap/ 🎉

**Pull request merged**
