### PR TITLE
Draft: Using Mona Sans Variable for all text

### PR DESCRIPTION
**Pull request by meyerweb**
null

----

Site preview: https://igalia.github.io/wpewebkit.org/gh-fonts/

### CODE REVIEW

**Comment by aperezdc** [comment]
In some instances the font shows odd behaviour. For example in the blue pill-buttons the outline of the fonts seems to be duplicated. You can see that in the following screenshot:

Screenshot of the preview site top-right button

**Comment by aperezdc** [comment]
Also: we already have a design style guide which specifies a font to use. If there is any issue with the current font, we should fix it instead of changing the font.

If we want to change the font used for branding WPE, I would say that needs discussion beforehand.

**Comment by meyerweb** [comment]
> Also: we already have a design style guide which specifies a font to use. If there is any issue with the current font, we should fix it instead of changing the font.
> 
> If we want to change the font used for branding WPE, I would say that needs discussion beforehand.

I believe this is a request by Denis to test out Mona and Hubot (the latter of which I dislike) as a common font to use, and I used wpewebkit.org as a testbed since it’s quick to change and build.

**Comment by aperezdc** [comment]
> > Also: we already have a design style guide which specifies a font to use. If there is any issue with the current font, we should fix it instead of changing the font.
> > If we want to change the font used for branding WPE, I would say that needs discussion beforehand.
> 
> I believe this is a request by Denis to test out Mona and Hubot (the latter of which I dislike) as a common font to use, and I used wpewebkit.org as a testbed since it’s quick to change and build.

Sure, no problem! Testing things is fine 😄

**Comment by bkardell** [comment]
We're going to just close this for now

**Pull request closed without merging**
