### PR TITLE
Remove old duplicated file, the current source is explore-wpe.md

### PR DESCRIPTION
**Pull request by manuelafm**
null

----

Site preview: https://igalia.github.io/wpewebkit.org/mafm-remove-exploring-md/

### CODE REVIEW

**Comment by bkardell** [comment]
I've checked the logs and we do get some traffic arriving at that URL from offsite searches, shares - so at least for some time we'll get some and I'd like to not just 404 them.  I'm putting together a redirect, and once that is set up we can merge this

**Comment by aperezdc** [comment]
@bkardell @manuelafm @meyerweb I am setting up a redirection in the HTTP server configuration right now, and I will take care of merging this right after the configuration is applied.

**Comment by aperezdc** [comment]
> @bkardell @manuelafm @meyerweb I am setting up a redirection in the HTTP server configuration right now, and I will take care of merging this right after the configuration is applied.

Done:

```
% curl -I https://wpewebkit.org/about/exploring.html       
HTTP/1.1 301 Moved Permanently
Date: Thu, 12 Jan 2023 18:56:43 GMT
Server: Apache/2.4.38 (Debian)
Strict-Transport-Security: max-age=63072000;
Location: https://wpewebkit.org/about/explore-wpe.html
Content-Type: text/html; charset=iso-8859-1

%
```

We can now merge this.

**Review by aperezdc — APPROVED** [review]

**Comment by bkardell** [comment]
really tho it should 301 to just /about @aperezdc - that's really the more appropriate replacement

**Comment by aperezdc** [comment]
> really tho it should 301 to just /about @aperezdc - that's really the more appropriate replacement

Thanks for the quick comment, it's not updated to point to `/about/`:

```
% curl -sI https://wpewebkit.org/about/exploring.html|grep Location:     
Location: https://wpewebkit.org/about/
%
```

**Pull request merged**
