### PR TITLE
Issue 61

### PR DESCRIPTION
**Pull request by meyerweb**
A very basic footer rework to add social-media links.

----

Site preview: https://igalia.github.io/wpewebkit.org/issue-61/

### CODE REVIEW

**Comment by meyerweb** [comment]
Take a look at https://igalia.github.io/wpewebkit.org/issue-61/ and see what you think.  I like the text-only aesthetic, and it helps in that instead of possibly-cryptic icons we have to size-balance and probably support with captions anyway, we can just use straight text and keep the file sizes smaller as a result.

**Comment by bkardell** [comment]
I think this is nice/fine

**Review by bkardell — APPROVED** [review]
LGTM, this is clearly and improvement to what we have there now, which is nothing - so I'm going to merge and suggest we can always polish more later if we want

**Review by bkardell — APPROVED** [review]

**Review by aperezdc — CHANGES_REQUESTED** [review]
The improved footer looks good, though I am afraid the PR needs to be rebased and conflicts solved before we can merge :memo:

**Comment by meyerweb** [comment]
Sorry about the conflicts—not quite sure how that happened.  What’s the preferred resolution strategy?

**Comment by aperezdc** [comment]
> Sorry about the conflicts—not quite sure how that happened. What’s the preferred resolution strategy?

Typically what I do is fetching the changes from the `master` and rebasing the work branch on top. So with your branch `issue-61` checked out, you would run `git fetch origin && git rebase origin/master`. If Git can resolve the conflicts itself, that will be it. Otherwise if it needs some help, it will let you know which files it has left with conflict markers. Edit them to your liking, let Git know with `git add <file>`, and then run `git rebase --continue`.

**Comment by meyerweb** [comment]
I can’t tell if I got it done or not.  Locally the branch appears to be fine, but when I push it says “Everything up-to-date”.  That’s after I had to abort rebasing because it got caught in a “you need to rebase/why are you rebasing, there are no changes” loop.  So… is the branch here still conflicted, and if so, now what?

**Comment by meyerweb** [comment]
Here’s a dump of what happened when I tried, from where I added (or THOUGHT I added) the recent changes. https://gist.github.com/meyerweb/0e56393d48231ce455f96ce930deabcc

**Review by aperezdc — APPROVED** [review]
@meyerweb Thanks, I see you did a couple of extra hoops, but managed to rebase and re-push the changes anyway—probably I could have been a bit clearer with the tip about how to do the dance with Git, sorry about that.

Let's merge this, then! :woman_dancing:

**Pull request merged**
