### PR TITLE
Alternative use case/success story resolution

### PR DESCRIPTION
**Pull request by bkardell**
We've had an open problem for some time that we'd like to highlight more in the main page, and the suggestion was to add a carousel with success stories or use cases.  For whatever reason we currently have 2 issues: First, we only have 2 approved entries. Carousels are already usually not a great choice for a bunch of reasons, but a carousel with only 2 things in it just seems weird, to be honest.  The other issue is that carousels should really contain "like" things and these are not - one is a use case and the other is a success story. So, there's been a PR for some time at #168 but it isn't deploying and also makes a specific choice there.

I just wanted to offer a very very simple alternative: Let's literally just put two things in that section until we get at least a third?

----

Site preview: https://igalia.github.io/wpewebkit.org/carousel/

### CODE REVIEW

**Comment by mariospr** [comment]
@bkardell The preview does not work, would you mind attaching a screenshot so that we can see how it looks?

**Comment by bkardell** [comment]
It would look basically like this.  Keep it simple:

Screenshot 2023-11-16 at 10 17 41 AM

**Comment by meyerweb** [comment]
I tweaked Brian’s work to balance things a bit more, and for better behavior across breakpoints.  Here’s a preview:

CleanShot 2023-11-16 at 13 09 20

Absent objections, I’ll deploy this some time on Friday, November 17th.

**Comment by mariospr** [comment]
@bkardell @meyerweb Thanks for the screenshots!

It looks good to me, but if I can add a suggestion, I'd rather reverse the order and put Metrological first, since I think it's the most relevant item in the list IMHO.

**Review by meyerweb — APPROVED** [review]

**Comment by mariospr** [comment]
Yay!

**Pull request merged**
